---
- name: Get the hosts facts
  hosts: all
  tasks: []

- name: Preparation
  hosts: clusters
  become: true
  tasks:
    - include_role:
        name: kubernetes
        tasks_from: preparation.yml

- name: Configure Load Balancer with Haproxy
  hosts: lb
  become: true
  tasks:
    - include_role:
        name: kubernetes
        tasks_from: load_balancer.yml

- name: Install and Configure Containerd
  hosts: clusters
  become: true
  tasks:
    - include_role:
        name: kubernetes
        tasks_from: containerd.yml

- name: Init Kubernetes Clusters on master01
  hosts: workers
  become: true
  tasks:
    - include_role:
        name: kubernetes
        tasks_from: init.yml

- name: Join worker nodes
  hosts: control_plane[1]
  become: true
  tasks:
    - include_role:
        name: kubernetes
        tasks_from: join_workers.yml