---
# vars file for kubernetes
master:
  hostname: 
   - master01
   - master02
  ip:
   - 10.20.0.7
   - 10.20.0.18
  cluster:
    kubernetes_version: "1.29.6"
    control_plane_endpoint: "10.20.0.21:6443"
    pod_subnet: "192.168.0.0/16"

lb:
  ip:
    lb01: 10.20.0.5
    lb02: 10.20.0.19
    vip: 10.20.0.21

packages:
  prerequisite:
    - curl
    - apt-transport-https
    - gpg
  
  kubernetes:
    - kubelet
    - kubeadm
    - kubectl

gpg_key:
  src: "https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key"

repository:
  kubernetes: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"