---
# handlers file for kubernetes
- name: Enable and start the containerd service
  service:
    name: containerd
    state: started
    enabled: yes

- name: Restart containerd service
  service:
    name: containerd
    state: restarted
    
- name: Restart haproxy service
  service:
    name: haproxy
    state: restarted

- name: Restart keepalived service
  service:
    name: keepalived
    state: restarted