---
- name: Create kubernetes cluster config file
  template:
    src: cluster.conf.j2
    dest: /tmp/kubeadm-config.yml

- name: Initialize the cluster
  shell: kubeadm init --config /tmp/kubeadm-config.yml --upload-certs
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init_result

- debug:
    var: kubeadm_init_result.stdout_lines

- name: Get the certificate key from the init output
  set_fact:
    cert_key: "{{ kubeadm_init_result.stdout | regex_search('certificate key: (.*)', '\\1') }}"

- name: Create a directory for kubeconfig (root user)
  file:
    state: directory
    path: /root/.kube/
    mode: 0775

- name: Setup kubeconfig for root user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    mode: 0644
    owner: root
    group: root
    remote_src: yes

- name: Create a directory for kubeconfig (non-root user)
  file:
    state: directory
    path: /home/{{ ansible_user_id }}/.kube/
    mode: 0775
  when: ansible_user_id != 'root'

# - name: Extract token and hash from join command
#   set_fact:
#     token: "{{ kubernetes_join_command.stdout | regex_search('--token ([^ ]+)', '\\1') }}"
#     ca_cert_hash: "{{ kubernetes_join_command.stdout | regex_search('--discovery-token-ca-cert-hash ([^ ]+)', '\\1') }}"

# - name: Save join information to a file
#   copy:
#     content: |
#       token: {{ token }}
#       ca_cert_hash: {{ ca_cert_hash }}
#       cert_key: {{ cert_key }}
#     dest: /tmp/join_info.yml

# - name: Fetch join information to controller
#   fetch:
#     src: /tmp/join_info.yml
#     dest: /tmp/join_info.yml
#     flat: yes
#   delegate_to: localhost
#   when: inventory_hostname == groups['control_plane'][0]

# - name: Distribute join information to other control planes
#   copy:
#     src: /tmp/join_info.yml
#     dest: /tmp/join_info.yml
#   delegate_to: "{{ item }}"
#   with_items: "{{ groups['control_plane'][1:] }}"
#   when: inventory_hostname == groups['control_plane'][0]

- name: Download Calico manifest
  get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml
    dest: /tmp/calico.yml

- name: Setup calico for kubernetes networking
  shell: sed -i 's/policy\/v1beta1/policy\/v1/g' /tmp/calico.yml && kubectl apply -f /tmp/calico.yml