---
- name: Create kubernetes cluster config file
  template:
    src: cluster.conf.j2
    dest: /tmp/kubeadm-config.yml

- name: Initialize the cluster
  shell: kubeadm init --config /tmp/kubeadm-config.yml --upload-certs
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init_result

- debug:
    var: kubeadm_init_result.stdout_lines

- name: Get the certificate key from the init output
  set_fact:
    cert_key: "{{ kubeadm_init_result.stdout | regex_search('--certificate-key ([a-f0-9a-fA-F]+)', '\\1') }}"

- name: Debug cert_key
  debug:
    msg: "{{ cert_key }}"

- name: Get the token for joining the control-plane nodes
  become: yes
  shell: kubeadm token create --print-join-command --certificate-key {{ cert_key }}
  register: kubernetes_join_command_control_plane

- debug:
    msg: "{{ kubernetes_join_command_control_plane.stdout }}"

- name: Copy control-plane join command to local
  copy:
    content: "{{ kubernetes_join_command_control_plane.stdout }}"
    dest: "/tmp/kubernetes_join_command_control_plane"
    mode: '0644'

- name: Create a directory for kubeconfig (root user)
  file:
    state: directory
    path: /root/.kube/
    mode: 0775

- name: Setup kubeconfig for root user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    mode: 0644
    owner: root
    group: root
    remote_src: yes

- name: Create a directory for kubeconfig (non-root user)
  file:
    state: directory
    path: /home/{{ ansible_user_id }}/.kube/
    mode: 0775
  when: ansible_user_id != 'root'

- name: Get the token for joining the worker nodes
  shell: kubeadm token create --print-join-command
  register: kubernetes_join_command

- debug:
   msg: "{{ kubernetes_join_command.stdout }}"

- name: Copy workers join command to local
  copy:
    content: "{{ kubernetes_join_command_workers.stdout }}"
    dest: "/tmp/kubernetes_join_command_workers"
    mode: '0644'

- name: Download Calico manifest
  get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml
    dest: /tmp/calico.yml

- name: Setup calico for kubernetes networking
  shell: sed -i 's/policy\/v1beta1/policy\/v1/g' /tmp/calico.yml && kubectl apply -f /tmp/calico.yml