---
# - name: Join Control Plane Node
#   shell: |
#     kubeadm join {{ lb.ip.vip }}:6443 --token {{ token }} --discovery-token-ca-cert-hash {{ ca_cert_hash }} --control-plane --certificate-key {{ cert_key }}
#   when: "'control_plane' in group_names"

- name: Get the token for joining the worker nodes
  shell: kubeadm token create --print-join-command
  register: kubernetes_join_command

- debug:
   msg: "{{ kubernetes_join_command.stdout }}"

- name: Copy join command to local file.
  copy: 
    content: "{{ kubernetes_join_command.stdout_lines[0] }}" 
    dest: "/tmp/kubernetes_join_command" 
    mode: 0777

- name: Join Worker Node
  command: sh /tmp/kubernetes_join_command
  register: joined_or_not