---
- name: Fetch join information to controller
  fetch:
    src: /tmp/join_info.yml
    dest: /tmp/join_info_{{ inventory_hostname }}.yml
    flat: yes

- name: Load join information
  include_vars:
    file: /tmp/join_info_{{ inventory_hostname }}.yml

- name: Join Control Plane Node
  shell: |
    kubeadm join {{ lb.ip.vip }}:6443 --token {{ token }} --discovery-token-ca-cert-hash {{ ca_cert_hash }} --control-plane --certificate-key {{ cert_key }}
  when: "'control_plane' in group_names"

- name: Join Worker Node
  shell: |
    kubeadm join {{ lb.ip.vip }}:6443 --token {{ token }} --discovery-token-ca-cert-hash {{ ca_cert_hash }}
  when: "'workers' in group_names"