---
- name: Configure host mapping
  template:
    src: templates/hosts.j2
    dest: "/etc/hosts"
  
- name: Set the hostname
  hostname:
    name: "{{ hostvars[inventory_hostname]['hostname'] }}"

- name: Update apt package index
  apt:
    update_cache: yes

- name: Install prerequisite packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages.prerequisite }}"

- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Kubernetes official gpg key
  apt_key:
    url: "{{ gpg_key.src }}"
    state: present
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Configure Kubernetes repository
  apt_repository:
    repo: "{{ repository.kubernetes }}"
    state: present
    filename: kubernetes.list
    mode: 0600
  
- name: Update apt package index
  apt:
    update_cache: yes

- name: Create containerd configuration
  template:
    src: containerd.conf.j2
    dest: /etc/modules-load.d/containerd.conf

- name: Load modules
  shell: 
    cmd: "modprobe {{ item }}"
  loop:
    - overlay
    - br_netfilter

- name: Set system configuration for Kubernetes networking
  template:
    src: kubernetes-cri.conf.j2
    dest: /etc/sysctl.d/99-kubernetes-cri.conf

- name: Configure proc sys for Kubernetes networking
  shell: echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables && echo 1 > /proc/sys/net/ipv4/ip_forward

- name: Apply the system settings
  shell: sysctl --sytem && sysctl -p

- name: Disable swap
  shell: swapoff -a
  
- name: Comment out swap entry in /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^(.*\sswap\s.*)$'
    line: '#\1'
    validate: '/bin/cat %s'

- name: Install kubernetes packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages.kubernetes }}"

- name: Hold the packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: "{{ packages.kubernetes }}"